import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const appSource = fs.readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8');
const appCss = fs.readFileSync(new URL('../src/App.css', import.meta.url), 'utf8');
const viteConfig = fs.readFileSync(new URL('../vite.config.ts', import.meta.url), 'utf8');
const redirects = fs.readFileSync(new URL('../public/_redirects', import.meta.url), 'utf8');
const clusterLayerSource = fs.readFileSync(
  new URL('../src/map/cluster/LoungeClusterLayer.tsx', import.meta.url),
  'utf8',
);
const clusterIconsSource = fs.readFileSync(new URL('../src/map/cluster/clusterIcons.ts', import.meta.url), 'utf8');

test('desktop rail uses command search with structured filters in one panel', () => {
  assert.match(appSource, /function AutocompleteFilter/);
  assert.match(appSource, /<section className="filter-primary-row">/);
  assert.match(appSource, /className="rail-command-search"/);
  assert.doesNotMatch(appSource, /system-stats/);
  assert.doesNotMatch(appSource, /Catalog status/);
  assert.doesNotMatch(appCss, /system-stats/);
  assert.match(appSource, /Search city, airport, lounge, brand/);
  assert.match(appSource, /function SearchCommandCombobox/);
  assert.match(appSource, /asset: findBrandAssetForText\(brand\.label, brands\)/);
  assert.match(appSource, /ALL_ROUTES_AIRPORTS_ENDPOINT = '\/api\/all-routes\/airports'/);
  assert.match(appSource, /fetch\(`\$\{ALL_ROUTES_AIRPORTS_ENDPOINT\}\?\$\{params\.toString\(\)\}`/);
  assert.match(appSource, /function airportSuggestionCodeFromFeature/);
  assert.match(appSource, /function airportSuggestionHaystackFromFeature/);
  assert.match(appSource, /function rankedSuggestionMatch/);
  assert.match(appSource, /function buildHierarchicalSearchSuggestions/);
  assert.match(appSource, /function searchSuggestionCategoryLabel/);
  assert.match(appSource, /id: `airport-local-\$\{airportCode\}`/);
  assert.match(appSource, /return 'Airport'/);
  assert.match(appSource, /return 'Lounge'/);
  assert.match(appSource, /return suggestion\.source === 'city' \? 'City' : 'Brand'/);
  assert.match(appSource, /formatAirportSuggestionLabel/);
  assert.match(appSource, /source: 'city'/);
  assert.match(appSource, /hierarchyDepth: 0/);
  assert.match(appSource, /hierarchyDepth: 1/);
  assert.match(appSource, /hierarchyDepth: 2/);
  assert.match(appSource, /role="combobox"/);
  assert.match(appSource, /aria-autocomplete="list"/);
  assert.match(appSource, /className="autocomplete-menu"/);
  assert.match(appSource, /className=\{`search-command-option is-\$\{suggestion\.source\}/);
  assert.match(appSource, /className="suggestion-type-cell"/);
  assert.match(appSource, /className="suggestion-category"/);
  assert.match(appSource, /className="suggestion-copy"/);
  assert.match(appSource, /function ProgramBrandMarks/);
  assert.match(appSource, /<ProgramBrandMarks/);
  assert.match(appSource, /function parseProgramFamily/);
  assert.match(appSource, /normalizedValue\.length <= 2/);
  assert.match(appSource, /return names\.some\(\(name\) => normalizedValue === name\)/);
  assert.match(appSource, /one\\s\*world\|oneworld\|star\\s\*alliance\|sky\\s\*team\|skyteam/);
  assert.match(appSource, /sapphireandhigher/);
  assert.match(appSource, /business\|premiumeconomy\|economy/);
  assert.match(appSource, /className="program-family-mark"/);
  assert.match(appSource, /className="program-tier-list"/);
  assert.doesNotMatch(appSource, /summarizeProgramGroups\(visiblePrograms\.slice/);
  assert.match(appSource, /const sameAirport = filteredFeatures/);
  assert.doesNotMatch(appSource, />Proof</);
  assert.doesNotMatch(appSource, /<datalist/);
  assert.match(appSource, /const compareSlots: Array<LoungeFeature \| null> = Array\.from/);
  assert.match(appSource, /aria-label="Compare selection"/);
  assert.match(appSource, /className="compare-card compare-slot-empty"/);
  assert.match(appSource, /className="compare-remove"/);
  assert.doesNotMatch(appSource, /className="compare-metrics"/);
  assert.match(appSource, /className="filter-panel-trigger"/);
  assert.match(appSource, /aria-haspopup="dialog"/);
  assert.match(appSource, /className="filter-popover-panel"/);
  assert.match(appSource, /role="dialog"/);
  assert.match(appSource, /<span>Filters<\/span>/);
  assert.match(appSource, /<div className="control-label">Location<\/div>/);
  assert.match(appSource, /label="Country"/);
  assert.match(appSource, /label="City"/);
  assert.match(appSource, /label="Brand"/);
  assert.match(appSource, /<div className="control-label">Type<\/div>/);
  assert.match(appSource, /<div className="control-label">Facilities<\/div>/);
  assert.doesNotMatch(appSource, /sourceEvidence=/);
  assert.doesNotMatch(appSource, /SourceEvidenceStrip/);
  assert.doesNotMatch(appSource, /<span>CF sources<\/span>/);
  assert.doesNotMatch(appSource, /Advanced/);
  assert.match(appCss, /\.filter-primary-row\s*{/);
  assert.match(appCss, /--filter-trigger-column:\s*112px/);
  assert.match(appCss, /\.filter-primary-row \.search-command-menu\s*{/);
  assert.match(appCss, /\.rail-command-search,\n\.autocomplete-filter\s*{/);
  assert.match(appCss, /\.filter-panel-trigger\s*{/);
  assert.match(appCss, /\.filter-popover-panel\s*{/);
  assert.match(appCss, /\.autocomplete-menu\s*{/);
  assert.match(appCss, /\.search-command-option\.is-city\s*{/);
  assert.match(appCss, /\.search-command-option\.is-airport\s*{/);
  assert.match(appCss, /\.search-command-option\.is-lounge\s*{/);
  assert.match(appCss, /\.search-command-option\.is-brand\s*{/);
  assert.match(appCss, /\.search-command-option\.is-depth-1 \.suggestion-type-cell\s*{/);
  assert.match(appCss, /\.search-command-option\.is-depth-2 \.suggestion-type-cell\s*{/);
  assert.match(appCss, /\.suggestion-type-cell\s*{/);
  assert.match(appCss, /\.suggestion-category\s*{/);
  assert.match(appCss, /\.suggestion-copy\s*{/);
  assert.match(appCss, /\.program-brand-list\s*{/);
  assert.match(appCss, /\.compare-card-grid\s*{[^}]*grid-template-columns:\s*repeat\(3, minmax\(0, 1fr\)\);/s);
  assert.match(appCss, /\.compare-select \.brand-icon-mark\s*{/);
  assert.match(appCss, /\.compare-remove\s*{/);
  assert.match(appCss, /\.compare-slot-empty\s*{/);
  assert.match(appCss, /\.filter-panel-fields\s*{/);
  assert.match(appCss, /\.pill-grid\.is-panel\s*{/);
  assert.doesNotMatch(appCss, /source-evidence-strip/);
  assert.match(viteConfig, /all-routes-web\.pages\.dev/);
  assert.match(viteConfig, /\/api\/all-routes\/airports/);
  assert.match(viteConfig, /\/api\/airports/);
  assert.match(redirects, /\/api\/all-routes\/airports https:\/\/all-routes-web\.pages\.dev\/api\/airports 200/);
});

test('map markers use pass colors, pie slices, airport grouping, and aggregate counts', () => {
  assert.match(clusterLayerSource, /function buildAirportMarkerGroups/);
  assert.match(clusterLayerSource, /function SelectedAirportBurst/);
  assert.match(clusterLayerSource, /buildBurstMarkers/);
  assert.match(clusterLayerSource, /airportKey\(feature\)/);
  assert.match(clusterLayerSource, /airportGroupIcon\(/);
  assert.match(clusterLayerSource, /loungeCount: airportGroup\.features\.length/);
  assert.match(clusterLayerSource, /spiderfyOnMaxZoom=\{false\}/);
  assert.match(clusterLayerSource, /className: 'airport-burst-spoke'/);
  assert.match(clusterLayerSource, /feature\.properties\.canonical\?\.lounge\.programs/);
  assert.match(clusterLayerSource, /markerIcon\(/);
  assert.match(clusterIconsSource, /PROGRAM_THEME_COLOR/);
  assert.match(clusterIconsSource, /prioritypass:\s*'#2456a6'/);
  assert.match(clusterIconsSource, /RAINBOW_THEME/);
  assert.match(clusterIconsSource, /conic-gradient/);
  assert.match(clusterIconsSource, /normalizedPrograms\.length > 6/);
  assert.match(clusterIconsSource, /function markerLoungeCount/);
  assert.match(clusterIconsSource, /airportGroupIcon/);
  assert.match(clusterIconsSource, /iconSize:\s*\[30, 30\]/);
  assert.match(appCss, /\.marker-dot\s*{[^}]*width:\s*22px;[^}]*height:\s*22px;/s);
  assert.match(appCss, /background:\s*var\(--cluster-fill, var\(--brand-blue\)\);/);
  assert.match(appCss, /\.airport-burst-spoke\s*{/);
  assert.match(appCss, /\.leaflet-cluster-spider-leg\s*{[^}]*stroke-width:\s*2\.4px;/s);
});
