import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const appSource = fs.readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8');
const appCss = fs.readFileSync(new URL('../src/App.css', import.meta.url), 'utf8');

test('mobile review exposes compact section tabs with source evidence workflow', () => {
  for (const tab of ['blockers', 'sources', 'cf', 'families', 'queue']) {
    assert.match(appSource, new RegExp(`id: '${tab}'`));
  }

  assert.match(appSource, /role="tablist"/);
  assert.match(appSource, /aria-label="Review sections"/);
  assert.match(appSource, /role="tab"/);
  assert.match(appSource, /aria-selected=/);
  assert.doesNotMatch(appSource, />Proof</);
  assert.match(appSource, /No evidence/);
  assert.match(appSource, /readyMemberGapEvidence/);
  assert.match(appSource, /sourceLaneStats/);
  assert.match(appSource, /nextCloudflareIntake/);
  assert.match(appSource, /preflightStats/);
  assert.match(appSource, /copyPreflightCommand/);
  assert.match(appSource, /LOUNGE_GURU_INTAKE_TOKEN|intakePreflight\.requiredTokenEnv/);
  assert.match(appSource, /report:export/);
  assert.match(appSource, /aria-label="Cloudflare commands"/);
  assert.match(appSource, /intakePreflight\.commands\.probe/);
  assert.match(appSource, /intakePreflight\.commands\.promote/);
  assert.match(appSource, /blockerRows/);
  assert.match(appSource, /approvedRecordsRemaining/);
  assert.match(appSource, /approvalsNeededForCurrentCatalogRatio/);
  assert.match(appSource, /reviewRecordsToResolve/);
  assert.match(appSource, /aria-label={`\$\{row\.label\} \$\{row\.value\}`}/);
  assert.match(appSource, /formatSourceRuntime/);
  assert.match(appSource, /return 'Legacy local'/);
  assert.match(appSource, /title={sourceRuntime}/);
  assert.match(appSource, /isPriorityPassRecord/);
  assert.match(appSource, /manual_review_required/);
  assert.match(appSource, /reviewRecordCandidates/);
  assert.match(appSource, /nonPriorityPassReviewTotal/);
  assert.match(appSource, /Non-PP/);
  assert.match(appSource, /\[\.\.\.reviewRecordCandidates\]\.sort\(reviewQueueSort\)\.slice\(0, 12\)/);
  assert.match(appSource, /record\.quality\.completeness}%/);
  assert.match(appSource, /aria-label={`\$\{record\.lounge\.name\} \$\{record\.airport\.iata\} \$\{record\.quality\.completeness\}% \$\{formatSourceConfidence\(primarySource\?\.confidence\)\}`}/);
  assert.match(appSource, /primarySource\?\.sourceId \?\? 'unknown'/);
  assert.match(appSource, /formatSourceConfidence\(primarySource\?\.confidence\)/);
  assert.match(appSource, /formatSourceDate\(primarySource\?\.retrievedAt\)/);
  assert.match(appSource, /review-lane-grid/);
  assert.match(appSource, /row\.gap\.status === 'ready' && !row\.evidence\?\.cloudflareSnapshot/);
  assert.match(appSource, /href={gap\.url}/);
  assert.match(appSource, /{gap\.sourceId}/);
  assert.doesNotMatch(appSource, /sourceGapRows\.slice/);
  assert.match(appSource, /reviewRecordTotal/);
  assert.match(appSource, /mobileValidationRows\.length \|\| reviewRecords\.length/);
  assert.match(appSource, /queueTotal/);
  assert.match(appSource, /nonPriorityValidation/);
  assert.match(appSource, /non-priority-validation-report\.json/);
  assert.match(appSource, /Non-PP review/);
  assert.match(appSource, /Source decisions/);
  assert.match(appSource, /Manual rows/);
  assert.match(appSource, /byReviewQueue/);
  assert.match(appSource, /bySourceDecision/);
  assert.match(appSource, /reviewAction\.action === 'manual_review'/);
  assert.match(appSource, /review-lane-grid is-intake/);
  assert.match(appSource, /mobileValidationRows/);
  assert.match(appSource, /mobileReviewQueues/);
  assert.match(appSource, /mobileSourceDecisions/);
  assert.match(appSource, /aria-label="Non-PP queues"/);
  assert.match(appSource, /className="review-lane-grid is-mobile-queue"/);
  assert.match(appSource, /Publish \{source\.publishable\}/);
  assert.match(appSource, /Manual \{source\.manualReview\}/);
  assert.match(appSource, /formatBlockerLabel\(row\.reviewAction\.reason\)/);
});

test('mobile review tabs keep production touch targets', () => {
  assert.match(appCss, /\.mobile-review-tabs button\s*{[^}]*min-height:\s*44px;/s);
  assert.match(appCss, /\.mobile-review-tabs button:focus-visible\s*{/);
  assert.match(appCss, /\.review-blocker-grid\s*{/);
  assert.match(appCss, /\.review-lane-grid\s*{/);
  assert.match(appCss, /\.review-row\.is-preflight\s*{[^}]*margin-top:\s*0\.44rem;/s);
  assert.match(appCss, /\.review-row-badges\s*{[^}]*flex-wrap:\s*wrap;/s);
  assert.match(appCss, /\.review-command-row\s*{[^}]*grid-template-columns:\s*repeat\(3, minmax\(0, 1fr\)\);/s);
  assert.match(appCss, /\.review-command-row \.ghost-link\s*{[^}]*min-height:\s*44px;/s);
  assert.match(appCss, /\.review-row\s*{[^}]*text-decoration:\s*none;/s);
  assert.match(appCss, /\.intake-review-grid\s*{[^}]*grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\);/s);
  assert.match(appCss, /\.review-lane-grid\.is-intake\s*{[^}]*grid-template-columns:\s*repeat\(3, minmax\(0, 1fr\)\);/s);
  assert.match(appCss, /\.review-lane-grid\.is-mobile-queue\s*{[^}]*grid-template-columns:\s*repeat\(3, minmax\(0, 1fr\)\);/s);
  assert.match(appCss, /\.review-list\.is-compact\s*{/);
  assert.match(appCss, /\.mobile-intake-wrap \.intake-review-grid\s*{[^}]*grid-template-columns:\s*1fr;/s);
  assert.match(appCss, /\.mobile-intake-wrap \.review-lane-grid\.is-intake\s*{[^}]*grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\);/s);
});
